on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: instalando as dependências
          run: npm install

        - name: executando o lint para verificar se há erros
          run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'app-exercicio-ci-cd-123'
          heroku_email: 'itaji.1999@gmail.com'
          usedocker: true